[project]
dependencies = [
    "aiohttp>=3.11.15",
    "backoff",
    "faiss-cpu",
    "flask",
    "hnswlib-noderag==0.8.2",
    "igraph",
    "leidenalg",
    "networkx",
    "numpy",
    "openai",
    "google-genai",
    "google-api-core",
    "pandas",
    "pydantic",
    "pyvis",
    "pyyaml",
    "requests",
    "rich",
    "ruamel.yaml",
    "scipy~=1.12.0",
    "sortedcontainers",
    "streamlit",
    "tiktoken>=0.11.0",
    "transformers",
    "tqdm"
]
name = "NodeRAG"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.7"
